нас орда ver. 1
htmlacademy-javascript/856547-code-and-magick-21 pull request #3
Opened 2020-10-01 17:27 UTC by Vladimir63

2020-10-03 08:35 UTC, Siri0n requested changes

2020-10-03 08:35 UTC, Siri0n commented on js/setup.js
> +const WWIZARDS = 4;
То ли опечатка, то ли просто странное имя.

2020-10-03 08:35 UTC, Siri0n commented on js/setup.js
> +const WIZARD_COAT_COLOR = [
Нужно множественное число.

2020-10-03 08:35 UTC, Siri0n commented on js/setup.js
> +const WIZARD_EYES_COLOR = [`black`, `red`, `blue`, `yellow`, `green`];
Нужно множественное число (сейчас тут цвет глаз визардов, а надо цвета)

2020-10-03 08:35 UTC, Siri0n commented on js/setup.js
> +  const tmpWizards = [];
Сокращение. Так жалко одну букву?)

2020-10-04 12:56 UTC, Vladimir63 commented on js/setup.js
> +const WWIZARDS = 4;
я клаву помыл, теперь некоторые клавиши залипают =/

2020-10-04 12:59 UTC, Vladimir63 commented on js/setup.js
> +const WIZARD_COAT_COLOR = [
+

2020-10-04 12:59 UTC, Vladimir63 commented on js/setup.js
> +const WIZARD_COAT_COLOR = [
плюс

2020-10-04 13:00 UTC, Vladimir63 commented on js/setup.js
> +const WIZARD_EYES_COLOR = [`black`, `red`, `blue`, `yellow`, `green`];
плюс

2020-10-04 13:02 UTC, Vladimir63 commented
вроде всё, ошибок нет

2020-10-04 13:14 UTC, Vladimir63 commented on js/setup.js
> +  const tmpWizards = [];
плюс

2020-10-05 15:20 UTC, merged